//---------------------------------------------------------------------
//PROMISE EXAMPLE
//---------------------------------------------------------------------
const fs = require('fs');
const superagent = require('superagent');

fs.readFile(`${__dirname}/dog.txt`, (err, data) => {
  //here is a callback ....
  console.log(`Breed, ${data}`);

  superagent
    //................................................................
    // CALLING PROMISE here ...
    //................................................................
    .get(`https://dog.ceo/api/breed/${data}/images/random`)

    //................................................................
    // SUCCESSFUL RETURNING OF PROMISE ...
    //................................................................
    .then((res) => {
      //here is another callback ...
      console.log('RETURNING Success of promise:', res.body);

      fs.writeFile('dog-img.txt', res.body.message, (err) => {
        //here is another callback...
        console.log('Random dog image saved to file!');
      });
    })

    //................................................................
    // ERROR RETURNING OF PROMISE...
    //................................................................
    .catch((err) => {
      console.log('RETURNED error of promise: ', err.message);
    });
});
